### ISSUE TITLE
isotope yields during the core collapse

### ISSUE THREAD

**Issue by tang-imp** [evanoconnor/GR1D#22]
We just began to learn GR1Dv2, a great tool developed by you and your collaborators. When we look the output .xg files, all the abundance of xa, xh, xn, xabar, xzbar are zero in the .xg files. We used the sample parameter file as the input.

Is it possible to generate the isotope abundances during the collapsing process?

**Comment by evanoconnor** [comment]
this should work now.  updating the many of the EOS variables requires calling the EOS directly instead of through the standard EOS call, that save times since we only interpolate exactly what we need for the calculation.  We don't need the mass fractions for the evolution.

Now the abundances should be in those files.

**Comment by tang-imp** [comment]
It works well now. Thanks a lot!

Best,
Xiaodong
